<a href="https://colab.research.google.com/github/Maruf0275/Machine-Learning-CIT/blob/main/Python-Libraries/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = [1,2,3,4,5]
data

[1, 2, 3, 4, 5]

In [3]:
print(type(data))

<class 'list'>

In [4]:
df = pd.Series(data)
df

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
print(type(df))

<class 'pandas.core.series.Series'>

In [6]:
df.info

<bound method Series.info of 0    1
1    2
2    3
3    4
4    5
dtype: int64>

In [7]:
df.info()

<class 'pandas.core.series.Series'>
RangeIndex: 5 entries, 0 to 4
Series name: None
Non-Null Count  Dtype
--------------  -----
5 non-null      int64
dtypes: int64(1)
memory usage: 172.0 bytes

In [9]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 50 ,40, 45],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
}
df = pd.DataFrame(data)
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   50      Chicago
3    David   40      Houston
4      Eva   45      Phoenix

In [10]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>